// automatically generated by the FlatBuffers compiler, do not modify

using System;
using FlatBuffers;

public struct MapInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static MapInfo GetRootAsMapInfo(ByteBuffer _bb) { return GetRootAsMapInfo(_bb, new MapInfo()); }
  public static MapInfo GetRootAsMapInfo(ByteBuffer _bb, MapInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public MapInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MapWidth { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MapHeight { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Grid? CollisionGrids(int j) { int o = __p.__offset(8); return o != 0 ? (Grid?)(new Grid()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int CollisionGridsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<MapInfo> CreateMapInfo(FlatBufferBuilder builder,
      int mapWidth = 0,
      int mapHeight = 0,
      VectorOffset collisionGridsOffset = default(VectorOffset)) {
    builder.StartObject(3);
    MapInfo.AddCollisionGrids(builder, collisionGridsOffset);
    MapInfo.AddMapHeight(builder, mapHeight);
    MapInfo.AddMapWidth(builder, mapWidth);
    return MapInfo.EndMapInfo(builder);
  }

  public static void StartMapInfo(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddMapWidth(FlatBufferBuilder builder, int mapWidth) { builder.AddInt(0, mapWidth, 0); }
  public static void AddMapHeight(FlatBufferBuilder builder, int mapHeight) { builder.AddInt(1, mapHeight, 0); }
  public static void AddCollisionGrids(FlatBufferBuilder builder, VectorOffset collisionGridsOffset) { builder.AddOffset(2, collisionGridsOffset.Value, 0); }
  public static void StartCollisionGridsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static Offset<MapInfo> EndMapInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<MapInfo>(o);
  }
};

